### ISSUE TITLE
ability to create output directory 

### ISSUE THREAD

**Issue by sb43** [cancerit/cgpCaVEManPostProcessing#19]
Error trying to open output file ../flagging_out/split.vcf.1: No such file or directory
This error arises when flagging_out directory doesn't exists.
flagging script should create output folder when it couldn't find one.

**Comment by drjsanger** [comment]
Should it create directories? How deep should we go with directory creation? Surely an error message where the directory does not exist suffices? Opinions @keiranmraine @sb43 ?
