### ISSUE TITLE
Need option so that actually fails when no flaglist found

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/cgpCaVEManPostProcessing#23]
The underlying cause of this test is a problem when debugging:

https://github.com/cancerit/cgpCaVEManPostProcessing/blob/7b17e9037644c5a5a1eef746e01e0fd15a82c088/t/cgpFlagCaVEMan.t#L107-L117

It should be possible to request the script give a non-zero exit code when no-flag list is found

**Comment by drjsanger** [comment]
Automatically dies now in  312c5cd58857e94de83cce12379f277f59a73fe6
