### ISSUE TITLE
Pre-release tag for fragment analysis

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/cgpCaVEManPostProcessing#26]
Based on `feature/overlapping_reads`
- [x] Ensure recent merge to dev is included #25
- [x] Fix up #17 
- [x] Create pre-release tag on `feature/overlapping_reads`

**Comment by drjsanger** [comment]
Release [1.8.0-rc1](https://github.com/cancerit/cgpCaVEManPostProcessing/archive/1.8.0-rc1.tar.gz) created

**Comment by drjsanger** [comment]
Released in [1.8.0](https://github.com/cancerit/cgpCaVEManPostProcessing/releases/tag/1.8.0)
