### ISSUE TITLE
Possible bug: cgpFlagCaVEMan.pl

### ISSUE THREAD

**Issue by jwhsanger** [cancerit/cgpCaVEManPostProcessing#6]
Hi Guys,

line 180

Initialisation of Vcf object

    my $vcf = Vcf->new(file=>$opts->{'f'}, -version=>'4.1');

has a dash in front of version key - is that intentional?

**Comment by keiranmraine** [comment]
Doesn't look like this causes an issue as the input VCF from CaVEMan is correctly defined as 4.1.  Checked against existing files generated with this code.  I have fixed it though.
